repos:
- hooks:
  - id: commitizen
    stages:
    - commit-msg
  repo: https://github.com/commitizen-tools/commitizen
  rev: v2.20.0
- hooks:
  - id: black
    language_version: python3.8
  repo: https://github.com/ambv/black
  rev: 22.3.0
- hooks:
  - id: flake8
    args:
          - "--max-line-length=99"
  repo: https://gitlab.com/pycqa/flake8
  rev: 3.9.2
- hooks:
  - args:
    - --django
    id: name-tests-test
  - id: requirements-txt-fixer
  - id: check-executables-have-shebangs
  repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.910-1
  hooks:
    - id: mypy